# REMOTE PUTIH
KW_POWER FD00FF
KW_MUTE FD807F
NUM_KW = [[1,"FDA05F"],[2,"FDC03F"],[3,"FD20DF"],[4,"FDA05F"],[5,"FD609F"],[6,"FDE01F"],[7,"FD10EF"],[8,"FD906F"],[9,"FD50AF"],[10,"FD30CF"]]
KW_SLEEP FDC23D
KW_VOLUP FD12ED
KW_VOLDOWN FD926D
KW_STUP FD52AD
KW_STDOWN FDD22D
KW_PLAY FD8A75
KW_STOP FD4AB5
KW_ENTER FD08F7
KW_TEN FDD02F #-/--
KW_SVOL FDB04F 
KW_
KW_
KW_
KW_
KW_
KW_
KW_
KW_
KW_
KW_
KW_
KW_
KW_